[package]
name = "monte_carlo_root"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = "26.0.1"
tokio = { version = "1.47.1", features = ["macros", "rt"] }
bytemuck = "1.23.1"

[dev-dependencies]
criterion = "0.6.0"

[[bench]]
name = "is_root_benchmark"
harness = false